export interface EmojiCategory {
  label: string
  emojis: { char: string; name: string }[]
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    label: 'Dev & Tech',
    emojis: [
      { char: '🗄️', name: 'database' },
      { char: '💾', name: 'disk' },
      { char: '🛢️', name: 'storage' },
      { char: '☁️', name: 'cloud' },
      { char: '🐳', name: 'docker' },
      { char: '💻', name: 'laptop' },
      { char: '🖥️', name: 'server' },
      { char: '📡', name: 'api' },
      { char: '🔗', name: 'link' },
      { char: '🔒', name: 'lock' },
      { char: '🔑', name: 'key' },
      { char: '⚙️', name: 'settings' },
      { char: '🔧', name: 'wrench' },
      { char: '🐛', name: 'bug' },
      { char: '🚀', name: 'rocket' },
      { char: '📦', name: 'package' },
      { char: '🌐', name: 'globe' },
      { char: '📊', name: 'chart' },
      { char: '📈', name: 'trending up' },
      { char: '🧩', name: 'puzzle' },
    ],
  },
  {
    label: 'Status',
    emojis: [
      { char: '✅', name: 'check' },
      { char: '❌', name: 'cross' },
      { char: '⚠️', name: 'warning' },
      { char: '🚧', name: 'construction' },
      { char: '🔥', name: 'fire' },
      { char: '⏳', name: 'hourglass' },
      { char: '🕒', name: 'clock' },
      { char: '📌', name: 'pin' },
      { char: '🚩', name: 'flag' },
      { char: '💡', name: 'idea' },
      { char: '🎯', name: 'target' },
      { char: '⭐', name: 'star' },
    ],
  },
  {
    label: 'Smileys',
    emojis: [
      { char: '😀', name: 'grin' },
      { char: '😄', name: 'smile' },
      { char: '😅', name: 'sweat smile' },
      { char: '😂', name: 'joy' },
      { char: '🙂', name: 'slight smile' },
      { char: '😉', name: 'wink' },
      { char: '😎', name: 'cool' },
      { char: '🤔', name: 'thinking' },
      { char: '😴', name: 'sleeping' },
      { char: '😭', name: 'crying' },
      { char: '😡', name: 'angry' },
      { char: '🥳', name: 'party' },
    ],
  },
  {
    label: 'Gestures',
    emojis: [
      { char: '👍', name: 'thumbs up' },
      { char: '👎', name: 'thumbs down' },
      { char: '👌', name: 'ok' },
      { char: '🙏', name: 'pray' },
      { char: '👏', name: 'clap' },
      { char: '✋', name: 'hand' },
      { char: '🤝', name: 'handshake' },
      { char: '💪', name: 'muscle' },
    ],
  },
  {
    label: 'Objek',
    emojis: [
      { char: '📝', name: 'memo' },
      { char: '📄', name: 'document' },
      { char: '📁', name: 'folder' },
      { char: '📅', name: 'calendar' },
      { char: '📞', name: 'phone' },
      { char: '✉️', name: 'envelope' },
      { char: '🔔', name: 'bell' },
      { char: '🎉', name: 'party popper' },
      { char: '☕', name: 'coffee' },
      { char: '💰', name: 'money' },
    ],
  },
]
